apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress
spec:
  profile: default # Do not install CRDs or the control plane
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: infrastructure
      enabled: true
      k8s:
        service:
          ports:
            - name: http2
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              port: 443
              protocol: TCP
              targetPort: 8443
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: ingressgateway
  values:
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
        serviceAnnotations:
          service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: subnet-qhbqka5n
          service.cloud.tencent.com/pass-to-target: "true"
          service.cloud.tencent.com/security-groups: "sg-6eaq601v"
